controller_list:
  - name: fake_c_controller
    type: $(arg fake_execution_type)
    joints:
      - Motor_1
      - Motor_2
      - Motor_3
      - Motor_4
initial:  # Define initial robot poses per group
  - group: c
    pose: Home