c_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Motor_1
    - Motor_2
    - Motor_3
    - Motor_4
  gains:
    Motor_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Motor_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Motor_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Motor_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1