controller_list:
  - name: c_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Motor_1
      - Motor_2
      - Motor_3
      - Motor_4